services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    restart: always
    ports:
      - "4566:4566"
    volumes:
      - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
    environment:
      DEBUG: "1"
      SERVICES: "sns,sqs,s3"

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_config:/data/configdb
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    depends_on:
    - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URI}
      ME_CONFIG_BASICAUTH: "false"

  app:
    container_name: document-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    links:
      - mongo
      - localstack
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      DB: ${DBNAME}
      MONGO_URL: ${MONGO_URL}
      AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}

volumes:
  mongodb_data:
  mongodb_config: