apiVersion: v1
kind: Pod
metadata:
  name: agent-k8s
spec:
  containers:
  - name: jenkins-agent
    image: jenkins/inbound-agent:latest
    env:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=agent-k8s
      - JENKINS_SECRET=8580370ce0f0cac4d033e1afb4fb0eea824b29bd87c6ed54435ca6c77ddeab19
      - JENKINS_WEB_SOCKET=true

    volumeMounts:
      - name: agent-workdir
        mountPath: /var/jenkins

  volumes:
    - name: agent-workdir
      emptyDir: {}