services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  agent-golang:
    build:
      context: .
      dockerfile: golang.Dockerfile
    container_name: jenkins-agent-golang
    restart: always
    volumes:
      - jenkins_agent_golang:/var/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins

  agent-docker:
    build:
      context: .
      dockerfile: docker.Dockerfile
    container_name: jenkins-agent-docker
    restart: always
    volumes:
      - jenkins_agent_docker:/var/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins

  agent-kubectl:
    build:
      context: .
      dockerfile: kubectl.Dockerfile
    container_name: jenkins-agent-kubectl
    restart: always
    volumes:
      - jenkins-agent-kubectl:/var/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=agent-k8s
      - JENKINS_SECRET=c4e6de9aacd886eec6379d40acb91dd62f91b1085b1dcb9f07af937340fa8eed
      - JENKINS_WEB_SOCKET=true
    depends_on:
      - jenkins

volumes:
  jenkins_home:
  jenkins_agent_golang:
  jenkins_agent_docker:
  jenkins-agent-kubectl: